routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\WelcomeController;
use App\Http\Controllers\EmployeeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', function () {
    return view('welcome', [
    ]);
});

Route::get('/employee', function () {
    return view('employee.index',[
    ]);
});
Route::get('/company', function () {
    return view('company.index',[
    ]);
});

Route::resource('/employee', App\http\Controllers\EmployeeController::class);;
Route::resource('/company', App\http\Controllers\CompanyController::class);;

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    use HasFactory;
    protected $fillable = ['id','nama','alamat'];
    public $timestamps = false;

}

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    use HasFactory;
    protected $fillable = ['id','nama','atasan_id','company_id'];
    public $timestamps = false;

}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
 
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Company;

class CompanyController extends Controller
{
    public function index()
    {

        return view('company.index',[
        'companies' => Company::all()
    ]);

    }

    public function create()
    {
        return view('company.create');

    }

    public function store(Request $request)
    {
        $request->validate([
            'id' => 'integer',
            'nama' => 'required|string|max:255',
            'alamat' => 'required|string|max:255'
        ]);

        Company::create($request->all());
        return redirect()->route('company.index')->with('success', 'Company has been added!');
    }

    public function edit(Company $company)
    {
        return view('company.edit', compact('company'));

    }

    public function update(Request $request, Company $company)
    {
        $request->validate([
            'id' => 'integer',
            'nama' => 'required|string|max:255',
            'alamat' => 'required|string|max:255'
        ]);

        $company->update($request->all());

        return redirect()->route('company.index')->with('success', 'Company telah berhasil diupdate');


    }

    public function destroy(Company $company)
    {
        $company->delete();

        return redirect()->route('company.index')->with('Success', 'Comapny Berhasil di Hapus');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Employee;
use Illuminate\Http\Request;
use PhpParser\Node\Expr\Empty_;

class EmployeeController extends Controller
{
    public function index()
    {

        return view('employee.index',[
        'employees' => Employee::all()
    ]);

    }

    public function index2()
    {
        return view('welcome');
    }

    public function create()
    {
        return view('employee.create');

    }

    public function store(Request $request)
    {
        $request->validate([
            'id' => 'integer',
            'nama' => 'required|string|max:255',
            'atasan_id' => 'integer',
            'company_id' => 'required|int'
        ]);

        Employee::create($request->all());
        return redirect()->route('employee.index')->with('success', ' Your Employee has been added!');
    }

    public function edit(Employee $employee)
    {
        return view('employee.edit', compact('employee'));

    }

    public function update(Request $request, Employee $employee)
    {
        $request->validate([
            'id' => 'required',
            'nama' => 'required',
            'atasan_id' => 'required',
            'company_id' => 'required'
        ]);

        $employee->update($request->all());

        return redirect()->route('employee.index')->with('success', 'Kategori telah berhasil diupdate');


    }

    public function destroy(Employee $employee)
    {
        $employee->delete();

        return redirect()->route('employee.index')->with('Success', 'Employee Berhasil di Hapus');
    }
}

resources/views/company/create.blade.php
@extends('layouts.main')

@section('container')

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Create New Company</h1>
  </div>

  <div class="col-lg-8">
  <form method="post" action="{{ route('company.store') }}" class="mb-5" enctype="multipart/form-data">
    @csrf
    <div class="mb-3">
        <label for="id" class="form-label">ID</label>
        <input type="number" class="form-control" id="id"
        name="id">
      </div>
    <div class="mb-3">
      <label for="nama" class="form-label">Nama</label>
      <input type="text" class="form-control" id="nama"
      name="nama">
    </div>
    <div class="mb-3">
      <label for="alamat" class="form-label">Alamat</label>
      <input type="text" class="form-control" id="alamat"
      name="alamat">
    </div>
    <button type="submit" class="btn btn-primary">Create Company</button>
  </form>
</div>
@endsection

resources/views/company/edit.blade.php
@extends('layouts.main')

@section('container')

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Edit Company</h1>
  </div>

  <div class="col-lg-8">
  <form method="post" action="{{ route('company.update', $company->id) }}" class="mb-5"
    enctype="multipart/form-data">
    @csrf
    @method('put')
    <div class="mb-3">
        <label for="id" class="form-label">ID</label>
        <input type="number" class="form-control" id="id"
        name="id">
      </div>
    <div class="mb-3">
      <label for="nama" class="form-label">Nama</label>
      <input type="text" class="form-control" id="nama"
      name="nama">
    </div>
    <div class="mb-3">
      <label for="alamat" class="form-label">Alamat</label>
      <input type="text" class="form-control" id="alamat"
      name="alamat">
    </div>
    <button type="submit" class="btn btn-primary">Update Company</button>
  </form>
</div>
@endsection

resources/views/company/index.blade.php
@extends('layouts.main')


@section('container')
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">All Companys</h1>
  </div>


@if(session()->has('success'))
    <div class="alert alert-success col-lg-6" role="alert">
    {{  session('success') }}
    </div>
@endif
  <div class="table-responsive col-lg-6">
      <a href="{{ route('company.create') }}" class="btn btn-primary mb-3">Create New Company</a>
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Name</th>
          <th scope="col">Alamat</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
          @foreach ($companies as $company)
          <tr>
            <td>{{ $company->id }}</td>
            <td>{{ $company->nama}}</td>
            <td>{{ $company->alamat}}</td>
            <td>
                <a href="{{ route('company.edit',$company->id) }}" class="badge bg-warning">
                <span data-feather="edit"></span></a>
                <form action="{{ route('company.destroy',$company->id)}}" method="post" class="d-inline">
                @method('delete')
                @csrf
                <button class="badge bg-danger border-0" onclick="return confirm('Are you sure ?')">
                <span data-feather="x-circle"></span></button>
                </form>
            </td>
          </tr>
          @endforeach

      </tbody>
    </table>
  </div>
@endsection

resources/views/employee/create.blade.php
@extends('layouts.main')

@section('container')

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Create New Employee</h1>
  </div>

  <div class="col-lg-8">
  <form method="post" action="{{ route('employee.store') }}" class="mb-5" enctype="multipart/form-data">
    @csrf
    <div class="mb-3">
        <label for="id" class="form-label">ID</label>
        <input type="number" class="form-control" id="id"
        name="id">
      </div>
    <div class="mb-3">
      <label for="nama" class="form-label">Nama</label>
      <input type="text" class="form-control" id="nama"
      name="nama">
    </div>
    <div class="mb-3">
      <label for="atasan_id" class="form-label">Atasan ID</label>
      <input type="number" class="form-control " id="atasan_id"
      name="atasan_id">
    </div>
    <div class="mb-3">
      <label for="company_id" class="form-label">Company ID</label>
      <input type="number" class="form-control" id="company_id"
      name="company_id">
    </div>
    <button type="submit" class="btn btn-primary">Create Employee</button>
  </form>
</div>
@endsection

resources/views/employee/edit.blade.php
@extends('layouts.main')

@section('container')

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Edit Employee</h1>
  </div>

  <div class="col-lg-8">
  <form method="post" action="{{ route('employee.update', $employee->id) }}" class="mb-5"
    enctype="multipart/form-data">
    @csrf
    @method('put')
    <div class="mb-3">
        <label for="id" class="form-label">ID</label>
        <input type="number" class="form-control" id="id"
        name="id">
      </div>
    <div class="mb-3">
      <label for="nama" class="form-label">Nama</label>
      <input type="text" class="form-control" id="nama"
      name="nama">
    </div>
    <div class="mb-3">
      <label for="atasan_id" class="form-label">Atasan ID</label>
      <input type="number" class="form-control " id="atasan_id"
      name="atasan_id">
    </div>
    <div class="mb-3">
      <label for="company_id" class="form-label">Company ID</label>
      <input type="number" class="form-control" id="company_id"
      name="company_id">
    </div>
    <button type="submit" class="btn btn-primary">Update Employee</button>
  </form>
</div>
@endsection

resources/views/employee/index.blade.php
@extends('layouts.main')


@section('container')
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">All Employees</h1>
  </div>


@if(session()->has('success'))
    <div class="alert alert-success col-lg-6" role="alert">
    {{  session('success') }}
    </div>
@endif
  <div class="table-responsive col-lg-6">
      <a href="{{ route('employee.create') }}" class="btn btn-primary mb-3">Create New Employee</a>
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Name</th>
          <th scope="col">Atasan ID</th>
          <th scope="col">Company ID</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
          @foreach ($employees as $employee)
          <tr>
            <td>{{ $employee->id }}</td>
            <td>{{ $employee->nama}}</td>
            <td>{{ $employee->atasan_id}}</td>
            <td>{{ $employee->company_id}}</td>
            <td>
                <a href="{{ route('employee.edit',$employee->id) }}" class="badge bg-warning">
                <span data-feather="edit"></span></a>
                <form action="{{ route('employee.destroy',$employee->id)}}" method="post" class="d-inline">
                @method('delete')
                @csrf
                <button class="badge bg-danger border-0" onclick="return confirm('Are you sure ?')">
                <span data-feather="x-circle"></span></button>
                </form>
            </td>
          </tr>
          @endforeach

      </tbody>
    </table>
  </div>
@endsection

resources/views/layouts/header.blade.php
<header class="navbar navbar-dark sticky-top bg-primary flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">Employee</a>
    <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </header>

resources/views/layouts/main.blade.php
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Sturuktur Organisasi</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="/css/dashboard.css" rel="stylesheet">

     <style>
       trix-toolbar [data-trix-button-group="file-tools"] {
           display:none;
       }
     </style>
  </head>
  <body>

@include('layouts.header')

<div class="container-fluid">
  <div class="row">
   @include('layouts.sidebar')

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
    @yield('container')
    </main>
  </div>
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
 integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js"
integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script>

<script src="/js/dashboard.js"></script>
  </body>
</html>

resources/views/layouts/sidebar.blade.php
<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
    <div class="position-sticky pt-3">
      <ul class="nav flex-column">
        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1
        text-muted">
            <span>Dashboard Employee</span>
          </h6>

        <li class="nav-item">
          <a class="nav-link {{ Request::is('employee*') ? 'active' : ''}}" aria-current="page" href="employee">
            <span data-feather="file-text"></span>
            Employee
          </a>
        </li>

        <li class="nav-item">
          <a class="nav-link {{ Request::is('company*') ? 'active' : ''}}" href="company">
            <span data-feather="home"></span>
            Company
          </a>
        </li>
      </ul>
    </div>
  </nav>